// Code generated by anetos gen. DO NOT EDIT.

package models

import (
	"time"

	"anetos.dev/anetos/db"
)

// IssueCols are the columns of [Issue].
var IssueCols = struct {
	ID         db.Column[int64]
	CreatedAt  db.Column[time.Time]
	UpdatedAt  db.Column[time.Time]
	DeletedAt  db.Column[*time.Time]
	ProjectID  db.Column[int64]
	Number     db.Column[int]
	Title      db.Column[string]
	Body       db.Column[string]
	Status     db.Column[string]
	Priority   db.Column[string]
	AuthorID   db.Column[int64]
	AssigneeID db.Column[*int64]
	ClosedAt   db.Column[*time.Time]
}{
	ID:         db.Col[int64]("id"),
	CreatedAt:  db.Col[time.Time]("created_at"),
	UpdatedAt:  db.Col[time.Time]("updated_at"),
	DeletedAt:  db.Col[*time.Time]("deleted_at"),
	ProjectID:  db.Col[int64]("project_id"),
	Number:     db.Col[int]("number"),
	Title:      db.Col[string]("title"),
	Body:       db.Col[string]("body"),
	Status:     db.Col[string]("status"),
	Priority:   db.Col[string]("priority"),
	AuthorID:   db.Col[int64]("author_id"),
	AssigneeID: db.Col[*int64]("assignee_id"),
	ClosedAt:   db.Col[*time.Time]("closed_at"),
}

// IssueRels are the relations of [Issue], for With, Load and WhereHas.
var IssueRels = struct {
	Project     db.Rel[Issue, Project]
	Author      db.Rel[Issue, User]
	Assignee    db.Rel[Issue, User]
	Labels      db.Rel[Issue, Label]
	Comments    db.Rel[Issue, Comment]
	Attachments db.Rel[Issue, Attachment]
}{
	Project:     db.RelOf[Issue, Project]("Project"),
	Author:      db.RelOf[Issue, User]("Author"),
	Assignee:    db.RelOf[Issue, User]("Assignee"),
	Labels:      db.RelOf[Issue, Label]("Labels"),
	Comments:    db.RelOf[Issue, Comment]("Comments"),
	Attachments: db.RelOf[Issue, Attachment]("Attachments"),
}

// LabelCols are the columns of [Label].
var LabelCols = struct {
	ID        db.Column[int64]
	CreatedAt db.Column[time.Time]
	UpdatedAt db.Column[time.Time]
	ProjectID db.Column[int64]
	Name      db.Column[string]
	Color     db.Column[string]
}{
	ID:        db.Col[int64]("id"),
	CreatedAt: db.Col[time.Time]("created_at"),
	UpdatedAt: db.Col[time.Time]("updated_at"),
	ProjectID: db.Col[int64]("project_id"),
	Name:      db.Col[string]("name"),
	Color:     db.Col[string]("color"),
}

// CommentCols are the columns of [Comment].
var CommentCols = struct {
	ID        db.Column[int64]
	CreatedAt db.Column[time.Time]
	UpdatedAt db.Column[time.Time]
	IssueID   db.Column[int64]
	AuthorID  db.Column[int64]
	Body      db.Column[string]
}{
	ID:        db.Col[int64]("id"),
	CreatedAt: db.Col[time.Time]("created_at"),
	UpdatedAt: db.Col[time.Time]("updated_at"),
	IssueID:   db.Col[int64]("issue_id"),
	AuthorID:  db.Col[int64]("author_id"),
	Body:      db.Col[string]("body"),
}

// CommentRels are the relations of [Comment], for With, Load and WhereHas.
var CommentRels = struct {
	Author db.Rel[Comment, User]
}{
	Author: db.RelOf[Comment, User]("Author"),
}

// AttachmentCols are the columns of [Attachment].
var AttachmentCols = struct {
	ID          db.Column[int64]
	CreatedAt   db.Column[time.Time]
	UpdatedAt   db.Column[time.Time]
	IssueID     db.Column[int64]
	UploaderID  db.Column[int64]
	Name        db.Column[string]
	Path        db.Column[string]
	Size        db.Column[int64]
	ContentType db.Column[string]
}{
	ID:          db.Col[int64]("id"),
	CreatedAt:   db.Col[time.Time]("created_at"),
	UpdatedAt:   db.Col[time.Time]("updated_at"),
	IssueID:     db.Col[int64]("issue_id"),
	UploaderID:  db.Col[int64]("uploader_id"),
	Name:        db.Col[string]("name"),
	Path:        db.Col[string]("path"),
	Size:        db.Col[int64]("size"),
	ContentType: db.Col[string]("content_type"),
}

// AttachmentRels are the relations of [Attachment], for With, Load and WhereHas.
var AttachmentRels = struct {
	Uploader db.Rel[Attachment, User]
}{
	Uploader: db.RelOf[Attachment, User]("Uploader"),
}

// ProjectCols are the columns of [Project].
var ProjectCols = struct {
	ID          db.Column[int64]
	CreatedAt   db.Column[time.Time]
	UpdatedAt   db.Column[time.Time]
	Key         db.Column[string]
	Name        db.Column[string]
	Description db.Column[string]
	LastNumber  db.Column[int]
	ArchivedAt  db.Column[*time.Time]
}{
	ID:          db.Col[int64]("id"),
	CreatedAt:   db.Col[time.Time]("created_at"),
	UpdatedAt:   db.Col[time.Time]("updated_at"),
	Key:         db.Col[string]("key"),
	Name:        db.Col[string]("name"),
	Description: db.Col[string]("description"),
	LastNumber:  db.Col[int]("last_number"),
	ArchivedAt:  db.Col[*time.Time]("archived_at"),
}

// ProjectRels are the relations of [Project], for With, Load and WhereHas.
var ProjectRels = struct {
	Issues db.Rel[Project, Issue]
	Labels db.Rel[Project, Label]
}{
	Issues: db.RelOf[Project, Issue]("Issues"),
	Labels: db.RelOf[Project, Label]("Labels"),
}

// UserCols are the columns of [User].
var UserCols = struct {
	ID              db.Column[int64]
	CreatedAt       db.Column[time.Time]
	UpdatedAt       db.Column[time.Time]
	Name            db.Column[string]
	Email           db.Column[string]
	Password        db.Column[string]
	RememberToken   db.Column[string]
	SessionKey      db.Column[string]
	EmailVerifiedAt db.Column[*time.Time]
	DisabledAt      db.Column[*time.Time]
	TwoFactor       db.Column[string]
	PendingEmail    db.Column[string]
	Locale          db.Column[string]
	TimeZone        db.Column[string]
	Notify          db.Column[bool]
}{
	ID:              db.Col[int64]("id"),
	CreatedAt:       db.Col[time.Time]("created_at"),
	UpdatedAt:       db.Col[time.Time]("updated_at"),
	Name:            db.Col[string]("name"),
	Email:           db.Col[string]("email"),
	Password:        db.Col[string]("password"),
	RememberToken:   db.Col[string]("remember_token"),
	SessionKey:      db.Col[string]("session_key"),
	EmailVerifiedAt: db.Col[*time.Time]("email_verified_at"),
	DisabledAt:      db.Col[*time.Time]("disabled_at"),
	TwoFactor:       db.Col[string]("two_factor"),
	PendingEmail:    db.Col[string]("pending_email"),
	Locale:          db.Col[string]("locale"),
	TimeZone:        db.Col[string]("time_zone"),
	Notify:          db.Col[bool]("notify"),
}
