// Code generated by anetos add. DO NOT EDIT.

package main

import (
	"anetos.dev/anetos/ext"

	postmark "anetos.dev/anetos/plugins/postmark"
)

// plugins returns the app's plugins, in the order they were added:
// anetos add and anetos remove rewrite this file. setup loads them with
// ext.Load.
func plugins() []ext.Plugin {
	return []ext.Plugin{
		postmark.Plugin(),
	}
}
