// SPDX-License-Identifier: Apache-2.0

package db

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"slices"
	"strings"
	"time"
)

// Model hooks: implement any of these on a model's pointer type to run
// code around [Create], [Update], [Save] and [Delete]. A hook's error
// aborts the operation (run it in [Tx] to undo earlier writes). Save hooks
// run around both creates and updates, outside the create and update
// hooks. [CreateMany] runs the create hooks for each row; mass updates and
// deletes on a query, [Restore] and [Upsert] run none.

// BeforeCreateHook runs before a row is inserted.
type BeforeCreateHook interface {
	// BeforeCreate runs in the insert's context; an error stops the insert.
	BeforeCreate(ctx context.Context) error
}

// AfterCreateHook runs after a row is inserted.
type AfterCreateHook interface {
	// AfterCreate runs after the insert; an error is returned by Create.
	AfterCreate(ctx context.Context) error
}

// BeforeUpdateHook runs before a row is updated.
type BeforeUpdateHook interface {
	// BeforeUpdate runs in the update's context; an error stops the update.
	BeforeUpdate(ctx context.Context) error
}

// AfterUpdateHook runs after a row is updated.
type AfterUpdateHook interface {
	// AfterUpdate runs after the update; an error is returned by Update.
	AfterUpdate(ctx context.Context) error
}

// BeforeSaveHook runs before a row is inserted or updated.
type BeforeSaveHook interface {
	// BeforeSave runs before an insert or update; an error stops it.
	BeforeSave(ctx context.Context) error
}

// AfterSaveHook runs after a row is inserted or updated.
type AfterSaveHook interface {
	// AfterSave runs after an insert or update; an error is returned.
	AfterSave(ctx context.Context) error
}

// BeforeDeleteHook runs before a row is deleted or soft-deleted.
type BeforeDeleteHook interface {
	// BeforeDelete runs in the delete's context; an error stops the delete.
	BeforeDelete(ctx context.Context) error
}

// AfterDeleteHook runs after a row is deleted or soft-deleted.
type AfterDeleteHook interface {
	// AfterDelete runs after the delete; an error is returned by Delete.
	AfterDelete(ctx context.Context) error
}

func runHooks(ctx context.Context, row any, phase string) error {
	var err error
	switch phase {
	case "beforeCreate":
		if h, ok := row.(BeforeSaveHook); ok {
			if err = h.BeforeSave(ctx); err != nil {
				break
			}
		}
		if h, ok := row.(BeforeCreateHook); ok {
			err = h.BeforeCreate(ctx)
		}
	case "afterCreate":
		if h, ok := row.(AfterCreateHook); ok {
			if err = h.AfterCreate(ctx); err != nil {
				break
			}
		}
		if h, ok := row.(AfterSaveHook); ok {
			err = h.AfterSave(ctx)
		}
	case "beforeUpdate":
		if h, ok := row.(BeforeSaveHook); ok {
			if err = h.BeforeSave(ctx); err != nil {
				break
			}
		}
		if h, ok := row.(BeforeUpdateHook); ok {
			err = h.BeforeUpdate(ctx)
		}
	case "afterUpdate":
		if h, ok := row.(AfterUpdateHook); ok {
			if err = h.AfterUpdate(ctx); err != nil {
				break
			}
		}
		if h, ok := row.(AfterSaveHook); ok {
			err = h.AfterSave(ctx)
		}
	case "beforeDelete":
		if h, ok := row.(BeforeDeleteHook); ok {
			err = h.BeforeDelete(ctx)
		}
	case "afterDelete":
		if h, ok := row.(AfterDeleteHook); ok {
			err = h.AfterDelete(ctx)
		}
	}
	return err
}

// target resolves the database and model metadata for a write.
func target[T any](ctx context.Context) (*DB, conn, *meta, error) {
	m, err := metaOf(reflect.TypeFor[T]())
	if err != nil {
		return nil, nil, nil, err
	}
	d, c, err := handle(ctx)
	if err != nil {
		return nil, nil, nil, err
	}
	return d, c, m, nil
}

func setTime(v reflect.Value, m *meta, col int, t time.Time, onlyIfZero bool) {
	if col < 0 {
		return
	}
	f := fieldAlloc(v, m.cols[col].index)
	if onlyIfZero && !f.IsZero() {
		return
	}
	switch f.Type() {
	case timeType:
		f.Set(reflect.ValueOf(t))
	case timePtrType:
		f.Set(reflect.ValueOf(&t))
	}
}

// Create inserts row. A zero integer primary key is generated by the
// database and set on row. Models with [Timestamps] get created_at and
// updated_at set (unless already set).
func Create[T any](ctx context.Context, row *T) error {
	d, _, m, err := target[T](ctx)
	if err != nil {
		return err
	}
	return d.watched(ctx, m, func(ctx context.Context, ws []watch) error {
		_, c, err := handle(ctx)
		if err != nil {
			return err
		}
		if err := runHooks(ctx, row, "beforeCreate"); err != nil {
			return err
		}
		v := reflect.ValueOf(row).Elem()
		t := now(ctx)
		setTime(v, m, m.createdAt, t, true)
		setTime(v, m, m.updatedAt, t, true)
		if err := insert(ctx, d, c, m, []reflect.Value{v}, nil, nil); err != nil {
			return err
		}
		if ws != nil {
			k, err := rowKey(v, m)
			if err != nil {
				return err
			}
			after, err := valuesOf(v, m, m.stored()) // readonly columns: the database's, unknown here
			if err != nil {
				return err
			}
			if err := notify(ctx, ws, &Write{Op: OpCreate, Table: m.table, Key: k, After: after}); err != nil {
				return err
			}
		}
		return runHooks(ctx, row, "afterCreate")
	})
}

// CreateMany inserts rows in as few statements as possible, running the
// create hooks for each row. Generated primary keys are set on the rows on
// PostgreSQL and SQLite, but not on MySQL, which can't report them for a
// multi-row insert.
func CreateMany[T any](ctx context.Context, rows []T) error {
	if len(rows) == 0 {
		return nil
	}
	d, _, m, err := target[T](ctx)
	if err != nil {
		return err
	}
	return d.watched(ctx, m, func(ctx context.Context, ws []watch) error {
		_, c, err := handle(ctx)
		if err != nil {
			return err
		}
		t := now(ctx)
		vs := make([]reflect.Value, len(rows))
		for i := range rows {
			if err := runHooks(ctx, &rows[i], "beforeCreate"); err != nil {
				return err
			}
			vs[i] = reflect.ValueOf(&rows[i]).Elem()
			setTime(vs[i], m, m.createdAt, t, true)
			setTime(vs[i], m, m.updatedAt, t, true)
		}
		if ws != nil && m.autoPK && !d.dialect.Returning() {
			// The watchers need every row's key, which a multi-row insert
			// can't report on this database (MySQL).
			for _, v := range vs {
				if err := insert(ctx, d, c, m, []reflect.Value{v}, nil, nil); err != nil {
					return err
				}
			}
		} else if err := insert(ctx, d, c, m, vs, nil, nil); err != nil {
			return err
		}
		if ws != nil {
			limit := bulkValuesOf(ws)
			bulk := &Bulk{Keys: make([]any, 0, len(vs))}
			for _, v := range vs {
				k, err := rowKey(v, m)
				if err != nil {
					return err
				}
				bulk.Keys = append(bulk.Keys, k)
				if len(bulk.After) < limit {
					vals, err := valuesOf(v, m, m.stored())
					if err != nil {
						return err
					}
					bulk.After = append(bulk.After, RowValues{k, vals})
				}
			}
			bulk.Complete = len(bulk.After) == len(bulk.Keys)
			if err := notify(ctx, ws, &Write{Op: OpCreate, Table: m.table, Bulk: bulk}); err != nil {
				return err
			}
		}
		for i := range rows {
			if err := runHooks(ctx, &rows[i], "afterCreate"); err != nil {
				return err
			}
		}
		return nil
	})
}

// Upsert inserts rows, or updates the columns in update of rows that
// conflict with an existing one on the conflict columns (which need a
// unique index). With no update columns, conflicting rows are left as
// they are. Models with [Timestamps] also update updated_at. Hooks don't
// run, and generated keys aren't set on rows.
//
//	err := db.Upsert(ctx, prices, []string{"sku"}, "price")
func Upsert[T any](ctx context.Context, rows []T, conflict []string, update ...string) error {
	if len(rows) == 0 {
		return nil
	}
	if len(conflict) == 0 {
		return errors.New("db: Upsert needs conflict columns")
	}
	d, c, m, err := target[T](ctx)
	if err != nil {
		return err
	}
	for _, col := range slices.Concat(conflict, update) {
		if _, ok := m.byName[col]; !ok {
			return fmt.Errorf("db: Upsert: %s has no column %q", m.typ, col)
		}
	}
	if len(update) > 0 && m.updatedAt >= 0 && !slices.Contains(update, m.cols[m.updatedAt].name) {
		update = append(slices.Clip(update), m.cols[m.updatedAt].name)
	}
	t := now(ctx)
	vs := make([]reflect.Value, len(rows))
	for i := range rows {
		vs[i] = reflect.ValueOf(&rows[i]).Elem()
		setTime(vs[i], m, m.createdAt, t, true)
		setTime(vs[i], m, m.updatedAt, t, true)
	}
	if d.watchersOf(m.table) == nil {
		return insert(ctx, d, c, m, vs, conflict, update)
	}
	return d.watched(ctx, m, func(ctx context.Context, ws []watch) error {
		return upsertWatched[T](ctx, ws, m, vs, conflict, update)
	})
}

// upsertWatched upserts rows on a watched table: it reads the rows that
// conflict FOR UPDATE, upserts, reads them all back, and tells the
// watchers which rows were created and which updated (from what to what),
// telling them apart by primary key. Rows that conflicted with no columns
// to update weren't written. A conflict value that is NULL, or a zero
// generated key, never conflicts and can't find its row again, so it is
// refused.
//
// A conflicting row another transaction inserts between the read and the
// upsert is reported as created (its creator's entry says so too).
func upsertWatched[T any](ctx context.Context, ws []watch, m *meta, vs []reflect.Value, conflict, update []string) error {
	d, c, err := handle(ctx)
	if err != nil {
		return err
	}
	ccols := make([]int, len(conflict))
	for i, name := range conflict {
		ccols[i] = m.byName[name]
	}
	var ucols []int
	for _, name := range update {
		if ci := m.byName[name]; ci != m.updatedAt {
			ucols = append(ucols, ci)
		}
	}
	// The conflict values of every row, checked.
	tuples := make([][]any, len(vs))
	for i, v := range vs {
		tuples[i] = make([]any, len(ccols))
		for j, ci := range ccols {
			a, err := fieldArg(v, m.cols[ci])
			if err != nil {
				return err
			}
			if plainValue(a, m.cols[ci].json) == nil || ci == m.pk && m.autoPK && isZeroField(v, m.cols[ci].index) {
				return fmt.Errorf("db: Upsert on %s, which is watched, needs a value in every conflict column (%s is NULL or a generated key): such a row never conflicts, so it can't be found again", m.table, m.cols[ci].name)
			}
			tuples[i][j] = a
		}
	}
	// read returns the rows matching the conflict values, 500 at a time,
	// with col IN (…) or (a, b) IN ((…), …).
	read := func(lock bool) ([]T, error) {
		var out []T
		for chunk := range slices.Chunk(tuples, 500) {
			var cond Expr
			if len(ccols) == 1 {
				vals := make([]any, len(chunk))
				for i, t := range chunk {
					vals[i] = t[0]
				}
				cond = inExpr{m.table + "." + m.cols[ccols[0]].name, vals, false}
			} else {
				names := make([]string, len(ccols))
				for j, ci := range ccols {
					names[j] = quoteName(d.dialect, m.table+"."+m.cols[ci].name)
				}
				one := "(" + strings.TrimSuffix(strings.Repeat("?, ", len(ccols)), ", ") + ")"
				var args []any
				for _, t := range chunk {
					args = append(args, t...)
				}
				cond = SQL("("+strings.Join(names, ", ")+") IN ("+strings.TrimSuffix(strings.Repeat(one+", ", len(chunk)), ", ")+")", args...)
			}
			q := Query[T](ctx).WithTrashed().Where(cond).OrderBy(C(m.table + "." + m.cols[m.pk].name).Asc())
			if lock {
				q = q.ForUpdate()
			}
			got, err := q.Get()
			if err != nil {
				return nil, err
			}
			out = append(out, got...)
		}
		return out, nil
	}
	existing, err := read(true)
	if err != nil {
		return err
	}
	had := make(map[string]Values, len(existing)) // by primary key
	for i := range existing {
		v := reflect.ValueOf(&existing[i]).Elem()
		k, err := rowKey(v, m)
		if err != nil {
			return err
		}
		vals, err := valuesOf(v, m, ucols)
		if err != nil {
			return err
		}
		had[fmt.Sprintf("%#v", k)] = vals
	}
	if err := insert(ctx, d, c, m, vs, conflict, update); err != nil {
		return err
	}
	written, err := read(false)
	if err != nil {
		return err
	}
	limit := bulkValuesOf(ws)
	bulk := &Bulk{}
	complete := true
	for i := range written {
		v := reflect.ValueOf(&written[i]).Elem()
		k, err := rowKey(v, m)
		if err != nil {
			return err
		}
		before, existed := had[fmt.Sprintf("%#v", k)]
		if existed && len(update) == 0 {
			continue // left as it was
		}
		bulk.Keys = append(bulk.Keys, k)
		if len(bulk.After) >= limit {
			complete = false
			continue
		}
		var after Values
		if existed {
			bulk.Before = append(bulk.Before, RowValues{k, before})
			after, err = valuesOf(v, m, ucols)
		} else {
			after, err = valuesOf(v, m, nil)
		}
		if err != nil {
			return err
		}
		bulk.After = append(bulk.After, RowValues{k, after})
	}
	if len(bulk.Keys) == 0 {
		return nil
	}
	bulk.Complete = complete
	return notify(ctx, ws, &Write{Op: OpUpsert, Table: m.table, Bulk: bulk})
}

// maxParams keeps a statement under every database's parameter limit
// (SQLite: 32766, PostgreSQL and MySQL: 65535).
const maxParams = 30000

// insert writes rows with one INSERT per batch. With conflict columns it
// upserts instead and doesn't read back keys.
func insert(ctx context.Context, d *DB, c conn, m *meta, rows []reflect.Value, conflict, update []string) error {
	ctx = inBatch(ctx) // its chunks count as one query for repeated-query detection
	cols := m.insertable(rows[0])
	for _, r := range rows[1:] {
		if len(m.insertable(r)) != len(cols) {
			return errors.New("db: every row in one insert must set the primary key, or none may")
		}
	}
	generated := m.autoPK && !slices.Contains(cols, m.pk) && conflict == nil
	perBatch := max(1, maxParams/max(1, len(cols)))
	for start := 0; start < len(rows); start += perBatch {
		batch := rows[start:min(start+perBatch, len(rows))]
		b := &sqlBuilder{d: d.dialect}
		b.write("INSERT INTO ")
		b.name(m.table)
		if len(cols) == 0 {
			if len(batch) > 1 {
				return errors.New("db: can't insert several rows that have no columns to set")
			}
			b.write(" " + d.dialect.DefaultValues())
		} else {
			b.write(" (")
			for i, ci := range cols {
				if i > 0 {
					b.write(", ")
				}
				b.name(m.cols[ci].name)
			}
			b.write(") VALUES ")
			for ri, r := range batch {
				if ri > 0 {
					b.write(", ")
				}
				b.write("(")
				for i, ci := range cols {
					if i > 0 {
						b.write(", ")
					}
					a, err := fieldArg(r, m.cols[ci])
					if err != nil {
						return err
					}
					b.arg(a)
				}
				b.write(")")
			}
		}
		if conflict != nil {
			q := func(names []string) []string {
				out := make([]string, len(names))
				for i, n := range names {
					out[i] = d.dialect.QuoteIdent(n)
				}
				return out
			}
			b.write(" " + d.dialect.Upsert(q(conflict), q(update)))
		}
		if generated && d.dialect.Returning() {
			b.write(" RETURNING ")
			b.name(m.cols[m.pk].name)
			rows, err := d.query(ctx, c, b.String(), b.args)
			if err != nil {
				return err
			}
			i := 0
			for rows.Next() {
				if i < len(batch) {
					if err := rows.Scan(fieldAlloc(batch[i], m.cols[m.pk].index).Addr().Interface()); err != nil {
						rows.Close()
						return fmt.Errorf("db: scan generated key: %w", err)
					}
				}
				i++
			}
			if err := errors.Join(rows.Err(), rows.Close()); err != nil {
				return err
			}
			continue
		}
		res, err := d.exec(ctx, c, b.String(), b.args)
		if err != nil {
			return err
		}
		if generated && len(batch) == 1 {
			id, err := res.LastInsertId()
			if err != nil {
				return fmt.Errorf("db: read generated key: %w", err)
			}
			pk := fieldAlloc(batch[0], m.cols[m.pk].index)
			switch pk.Kind() {
			case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
				pk.SetUint(uint64(id))
			default:
				pk.SetInt(id)
			}
		}
	}
	return nil
}

func pkCond(v reflect.Value, m *meta) (Expr, error) {
	if m.pk < 0 {
		return nil, fmt.Errorf("db: %s has no primary key (tag a field db:\",pk\")", m.typ)
	}
	f := fieldOf(v, m.cols[m.pk].index)
	if !f.IsValid() || f.IsZero() {
		return nil, fmt.Errorf("db: %s has a zero primary key; Create it first", m.typ)
	}
	return cmpExpr{m.cols[m.pk].name, "=", f.Interface()}, nil
}

// Update writes every column of row (except the primary key, created_at
// and deleted_at) to its database row, found by primary key, and returns
// [ErrNotFound] if there is no such row. Models with [Timestamps] get
// updated_at set. Soft-deleted rows can be updated; use [Restore] to
// undelete one.
func Update[T any](ctx context.Context, row *T) error {
	d, _, m, err := target[T](ctx)
	if err != nil {
		return err
	}
	return d.watched(ctx, m, func(ctx context.Context, ws []watch) error {
		return update(ctx, ws, d, m, row)
	})
}

func update[T any](ctx context.Context, ws []watch, d *DB, m *meta, row *T) error {
	_, c, err := handle(ctx)
	if err != nil {
		return err
	}
	v := reflect.ValueOf(row).Elem()
	cond, err := pkCond(v, m)
	if err != nil {
		return err
	}
	if err := runHooks(ctx, row, "beforeUpdate"); err != nil {
		return err
	}
	var before Values
	if ws != nil {
		if before, err = readRow[T](ctx, v, m); err != nil {
			return err
		}
	}
	setTime(v, m, m.updatedAt, now(ctx), false)
	cols := m.updatable()
	if len(cols) == 0 {
		return runHooks(ctx, row, "afterUpdate")
	}
	b := &sqlBuilder{d: d.dialect}
	b.write("UPDATE ")
	b.name(m.table)
	b.write(" SET ")
	for i, ci := range cols {
		if i > 0 {
			b.write(", ")
		}
		b.name(m.cols[ci].name)
		b.write(" = ")
		a, err := fieldArg(v, m.cols[ci])
		if err != nil {
			return err
		}
		b.arg(a)
	}
	b.write(" WHERE ")
	cond.build(b)
	res, err := d.exec(ctx, c, b.String(), b.args)
	if err != nil {
		return err
	}
	if n, err := res.RowsAffected(); err == nil && n == 0 {
		return ErrNotFound
	}
	if ws != nil {
		k, err := rowKey(v, m)
		if err != nil {
			return err
		}
		after, err := afterUpdate(v, m, before)
		if err != nil {
			return err
		}
		if err := notify(ctx, ws, &Write{Op: OpUpdate, Table: m.table, Key: k, Before: before, After: after}); err != nil {
			return err
		}
	}
	return runHooks(ctx, row, "afterUpdate")
}

// Save creates row if its generated primary key is zero, and updates it
// otherwise. It is for models with an integer primary key; use Create and
// Update for others.
func Save[T any](ctx context.Context, row *T) error {
	m, err := metaOf(reflect.TypeFor[T]())
	if err != nil {
		return err
	}
	if !m.autoPK {
		return fmt.Errorf("db: Save needs an integer primary key; use Create or Update for %s", m.typ)
	}
	if isZeroField(reflect.ValueOf(row).Elem(), m.cols[m.pk].index) {
		return Create(ctx, row)
	}
	return Update(ctx, row)
}

// Delete deletes row, found by primary key. Models with [SoftDeletes] are
// soft-deleted: deleted_at is set in the database and on row. It returns
// [ErrNotFound] if no (non-deleted) row matched.
func Delete[T any](ctx context.Context, row *T) error {
	m, err := metaOf(reflect.TypeFor[T]())
	if err != nil {
		return err
	}
	return deleteRow(ctx, row, m.deletedAt >= 0)
}

// ForceDelete deletes row even if the model uses [SoftDeletes].
func ForceDelete[T any](ctx context.Context, row *T) error {
	return deleteRow(ctx, row, false)
}

func deleteRow[T any](ctx context.Context, row *T, soft bool) error {
	d, _, m, err := target[T](ctx)
	if err != nil {
		return err
	}
	return d.watched(ctx, m, func(ctx context.Context, ws []watch) error {
		return deleteWatched(ctx, ws, d, m, row, soft)
	})
}

func deleteWatched[T any](ctx context.Context, ws []watch, d *DB, m *meta, row *T, soft bool) error {
	_, c, err := handle(ctx)
	if err != nil {
		return err
	}
	v := reflect.ValueOf(row).Elem()
	cond, err := pkCond(v, m)
	if err != nil {
		return err
	}
	if err := runHooks(ctx, row, "beforeDelete"); err != nil {
		return err
	}
	var before Values
	if ws != nil && !soft {
		if before, err = readRow[T](ctx, v, m); err != nil {
			return err
		}
	}
	b := &sqlBuilder{d: d.dialect}
	t := now(ctx)
	if soft {
		b.write("UPDATE ")
		b.name(m.table)
		b.write(" SET ")
		b.name(m.cols[m.deletedAt].name)
		b.write(" = ")
		b.arg(t)
		if m.updatedAt >= 0 {
			b.write(", ")
			b.name(m.cols[m.updatedAt].name)
			b.write(" = ")
			b.arg(t)
		}
		b.write(" WHERE ")
		And(cond, C(m.cols[m.deletedAt].name).IsNull()).build(b)
	} else {
		b.write("DELETE FROM ")
		b.name(m.table)
		b.write(" WHERE ")
		cond.build(b)
	}
	res, err := d.exec(ctx, c, b.String(), b.args)
	if err != nil {
		return err
	}
	if n, err := res.RowsAffected(); err == nil && n == 0 {
		return ErrNotFound
	}
	if soft {
		setTime(v, m, m.deletedAt, t, false)
		setTime(v, m, m.updatedAt, t, false)
	}
	if ws != nil {
		k, err := rowKey(v, m)
		if err != nil {
			return err
		}
		w := &Write{Op: OpDelete, Table: m.table, Key: k}
		if !soft {
			w.Op, w.Before = OpForceDelete, before
		}
		if err := notify(ctx, ws, w); err != nil {
			return err
		}
	}
	return runHooks(ctx, row, "afterDelete")
}

// Restore undeletes a soft-deleted row.
func Restore[T any](ctx context.Context, row *T) error {
	d, _, m, err := target[T](ctx)
	if err != nil {
		return err
	}
	if m.deletedAt < 0 {
		return fmt.Errorf("db: %s doesn't use SoftDeletes", m.typ)
	}
	return d.watched(ctx, m, func(ctx context.Context, ws []watch) error {
		return restore(ctx, ws, d, m, row)
	})
}

func restore[T any](ctx context.Context, ws []watch, d *DB, m *meta, row *T) error {
	_, c, err := handle(ctx)
	if err != nil {
		return err
	}
	v := reflect.ValueOf(row).Elem()
	cond, err := pkCond(v, m)
	if err != nil {
		return err
	}
	t := now(ctx)
	b := &sqlBuilder{d: d.dialect}
	b.write("UPDATE ")
	b.name(m.table)
	b.write(" SET ")
	b.name(m.cols[m.deletedAt].name)
	b.write(" = NULL")
	if m.updatedAt >= 0 {
		b.write(", ")
		b.name(m.cols[m.updatedAt].name)
		b.write(" = ")
		b.arg(t)
	}
	b.write(" WHERE ")
	if ws != nil {
		// Only a deleted row is restored, so only a restore is recorded.
		cond = And(cond, C(m.cols[m.deletedAt].name).NotNull())
	}
	cond.build(b)
	res, err := d.exec(ctx, c, b.String(), b.args)
	if err != nil {
		return err
	}
	if ws != nil {
		if n, err := res.RowsAffected(); err == nil && n == 0 {
			fieldAlloc(v, m.cols[m.deletedAt].index).SetZero() // live already
			return nil                                         // nothing restored: nothing to tell
		}
	}
	fieldAlloc(v, m.cols[m.deletedAt].index).SetZero()
	setTime(v, m, m.updatedAt, t, false)
	if ws != nil {
		k, err := rowKey(v, m)
		if err != nil {
			return err
		}
		return notify(ctx, ws, &Write{Op: OpRestore, Table: m.table, Key: k})
	}
	return nil
}
